### ISSUE TITLE
[Bug] Token cannot be configured using a yaml file, but can be configured using environment variables

### ISSUE THREAD

**Issue by tyler0111** [selefra/selefra-provider-auth0#5]
When using the yaml file to configure Token, it prompts `Init client error: Config Error!` 

<img width="662" alt="image" src="https://user-images.githubusercontent.com/124039940/226262550-7a2b2834-84a2-4c23-a93a-57bdbcaf4967.png">

**Comment by monserrat101** [comment]
fixed with https://github.com/selefra/selefra-provider-auth0/releases/tag/v0.0.5
