### ISSUE TITLE
[Bug] The data in the database does not meet expectations

### ISSUE THREAD

**Issue by tyler0111** [selefra/selefra-provider-auth0#7]
The data in the database does not meet expectations, The data in some of the fields in the database are full json fields, and the expected result should be to populate the json content into each database column.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/124039940/226263567-710a0c60-534c-4d1e-9655-934d6cca20c9.png">
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/124039940/226263597-e6653993-dcca-4c1d-9c86-482304bc92ca.png">

**Comment by monserrat101** [comment]
table name ?

**Comment by tyler0111** [comment]
all tebles, eg auth0_client

**Comment by monserrat101** [comment]
fixed with https://github.com/selefra/selefra-provider-auth0/releases/tag/v0.0.6
